services:
  - type: web
    name: zeitapp
    env: node
    buildCommand: npm install -g vite && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
    nodeVersion: 20.11.1 